version: "3"

services: 
  app:
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment: 
      REDIS_HOST: redis
      DATABASE_URL: postgres://postgres:secret@db:5432/postgres
    volumes: 
      - ../:/workspace
    depends_on: [ redis, db ]
  
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    environment: 
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: db
    ports: [ 8080:8080 ]
  
  redis:
    image: redis